version: '3'

services:
  alphagamebot:
    image: alphagamedev/alphagamebot:latest
    restart: unless-stopped
    container_name: alphagamebot
    env_file:
      - .env

    # Make a file called ".env" and put one line, saying "TOKEN=<your token>  No spaces or quotes."
    # example:
    # TOKEN=mysupersecrettoken123pleasedontlookhahalol
