name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python run_tests.py
  dry_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bot
      run: python main.py --debug --dry-run --nodatabase --strict
    continue-on-error: false

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t alphagamedev/alphagamebot:testing .

      - name: Run Docker container
        run: |
          docker run --rm -i --name alphagamebot-testing alphagamedev/alphagamebot:testing --debug --dry-run --nodatabase --strict
        continue-on-error: false  # Fail the job if the container exits with a non-zero status